docs/Readme.md
This PR makes the readme look semi-decent :)
It basically closes #32
=> Niceify Readme

jails/mariadb/includes/my-system.cnf, jails/nextcloud/includes/Caddyfile-selfsigned, jails/nextcloud/install.sh
- Removes integrated Databases (fixes #33 )
- Moves Self-Signed certs to /config/ssl (standardisation)
=> Nextcloud-Cleanup for v1.1.0

jails/organizr/install.sh
=> Organizr: missing echo, fixes #46 

jailman.sh
Minor formatting cleanup around usage code.
=> Fixed destroyjails so it can destroy multiple jails. 

global.sh
This adds a restart reminder after automatic update as requested in #55
=> Add restart warning after update

global.sh, jails/nextcloud/install.sh
Adds central ports mount for all jails,
Also does auto fetch, extract and auto update on install
Closes #42
=> Add central ports mount for all jails

global.sh, jails/jackett/install.sh, jails/lidarr/install.sh, jails/radarr/install.sh, jails/sonarr/install.sh
=> Changed jail creation to always create base jails

docs/config options.md
- Adds documentation for config.yml options (fixes: #70)
- Describes the dataset structure, included auto-generated datasets (fixes: #68)
=> Add documentation for config options

config.yml.example, jailman.sh
Inspired by @danb35 it's actually relatively easy to just grab the iocage dataset automatically.
=> Automatically detect mountpoint for iocage

global.sh, jailman.sh, jails/bitwarden/install.sh, jails/bitwarden/update.sh, jails/influxdb/install.sh, jails/jackett/install.sh, jails/jackett/update.sh, jails/kms/install.sh, jails/kms/update.sh, jails/lidarr/install.sh, jails/lidarr/update.sh, jails/mariadb/includes/caddy, jails/mariadb/install.sh, jails/mariadb/update.sh, jails/nextcloud/includes/caddy, jails/nextcloud/install.sh, jails/organizr/install.sh, jails/organizr/update.sh, jails/plex/install.sh, jails/plex/update.sh, jails/radarr/install.sh, jails/radarr/update.sh, jails/sonarr/install.sh, jails/sonarr/update.sh, jails/transmission/install.sh
This PR cleans all current linter errors, or (if they are wrong/irrelevant) ignores them.
It fixes the already added fix for #38
and also adds most of the work needed for #48
=> Linter cleanup

config.yml.example, global.sh, jailman.sh
Some of the recent changes introduced new (high priority) bugs. This WIP is a bugfix PR
=> Fixes for recent changes

blueprints/unifi/install.sh
Minor fixes to unifi. Tested working with Grafana as well
=> Unifi fixes

blueprints/influxdb/install.sh, docs/Readme.md
I noticed a typo in InfluxDB install script, and I didn't add to README earlier. This fixes both.
=> Small InfluxDB typo fix

docs/CODEOWNERS
This PR adds code owners to the project
Please be aware: Write access is a requirement for code ownership. It's also a requirement for a codeowner or maintainer to approve changes to blueprints that are "owned" by a codeowner.
Hence it is given on a case-by-case basis and thus codeownership does not necessarily refer to the original creator of something.
=> add code owners

.shellcheckrc
Shellcheck SC2154 isn't compatible with this repo, because we use a lot of either dynamic or nested variables. Thus it can just-as-well be disabled
Please be aware this also means extra care needs to be taken to prevent referencing unset varaibles.
=> global shellcheck SC2154 fix

blueprints/bitwarden/update.sh
Just a small typo fix that would break updating for bitwarden jails
_Please enter any other relevant information here_
=> Correct datavase typo

global.sh, jailman.sh
This fix makes auto-update aware of the current checked-out branch using GIT.
It also checks for the old repository URL, and errors if thats still set.
(I might change this to an override instead)
It then updates to said branch, instead of our own.
Fixes #106
=> Make auto-update git aware

blueprints/bitwarden/config.yml, blueprints/jackett/install.sh, blueprints/lidarr/install.sh, blueprints/mariadb/config.yml, blueprints/nextcloud/config.yml, blueprints/nextcloud/install.sh, blueprints/organizr/config.yml, blueprints/transmission/update.sh
Some scripts used heavily outdated packages, packages that aren't actually needed and/or packages from ports where prebuild-binaries are available.
This updates things where updates where needed
Fixes #102
=> Update all the things/blueprints

docs/config options.md, global.sh
- Adds custom iocage create options to blueprint and jail config files.
Fixes #124
=> Add custom options for iocage-create to config files

blueprints/bazarr/config.yml, blueprints/bazarr/includes/bazarr.rc, blueprints/bazarr/install.sh, blueprints/bazarr/readme.md, blueprints/bazarr/update.sh, config.yml.example, docs/Readme.md
This Pull request adds a blueprint for Bazarr
https://github.com/morpheus65535/bazarr
=> Add Bazarr

config.yml.example, includes/global.sh
These are some small fixes for the just merged reinstall check and config file.
- Set the config.yml.example version to 1.3
- fix the reinstall path-check
=> Some small fixes

blueprints/forked_daapd/build-daapd.sh, blueprints/forked_daapd/build-ffmpeg.sh, blueprints/forked_daapd/config.yml, blueprints/forked_daapd/install.sh, blueprints/forked_daapd/readme.md, blueprints/forked_daapd/update.sh, config.yml.example, docs/CODEOWNERS, includes/global.sh
This PR adds a blueprint for forked-daapd with current ffmpeg.
I'm not quite sure yet what to do in the update script. Can you provide some feedback?
=> Add Forked_Daapd blueprint

blueprints/sabnzbd/config.yml, blueprints/sabnzbd/install.sh, blueprints/sabnzbd/readme.md, blueprints/sabnzbd/update.sh, config.yml.example, docs/CODEOWNERS, includes/global.sh
=> Add sabnzbd blueprint

blueprints/plex/config.yml, blueprints/plex/includes/hw_transcoding.sh, blueprints/plex/install.sh, blueprints/plex/readme.md, docs/CODEOWNERS
This PR ports the hardware transcoding patch by @thorsteneb from  to jailman.
It's designed to be as compact as possible and keeps the GPLv3 copyrighted code in a seperate function.
Needs additional testing
Fixes #139
=> Plex rework

blueprints/unifi/install.sh, blueprints/unifi/update.sh, jailman.sh
Fixes #151 Closes #151 
Edit:
Also Fixes #181 
Makes unifi_poller a boolean value, as described in the readme. poller will not install unless unifi_poller is true.
- [ x] Code is sufficiently commented
- [ x] Code is indented with tabs and not spaces
- [ x] The PR does not bring up any new errors
- [ x] The PR has been tested
=> Fix Unifi DB creation in InfluxDB
